language: cpp

# Use container-based infrastructure
sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    # we exceed the time limit
    - os: osx
  fast_finish: true

cache:
  # Enable compiler cache
  ccache: true
  # Caching Ubuntu packages
  apt: true
  # Caching other directories
  directories:
  - ${DEPENDENCIES_INSTALL}

addons:
  apt:
    sources: ['kalakris-cmake']
    packages:
    - cmake
    - libxerces-c-dev
    - openssl

before_install:
  - env | sort
  - date -u
  - uname -a
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      lsb_release -a;
      ccache -s;
    elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      sw_vers -productVersion;
    fi

script:
  - ./configure --build=x86_64 --enable-phdr --enable-as-02 --enable-dev-headers
  - make

# Before uploading the new cache archive
before_cache:
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      ccache -s;
    fi
